logging:
    level.ROOT: INFO
    level.org.springframework.test.web.servlet.result: DEBUG
spring:
    cloud:
        gcp:
            datastore:
                namespace: default
                project-id: syspro-344012
